# Build Stage:
FROM golang:1.18 as builder

## Install build dependencies.
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

## Add Source Code
ADD . /node-cert-exporter
WORKDIR /node-cert-exporter

## Build Step
RUN go mod tidy
RUN make
WORKDIR bin

# Package Stage
FROM debian:bookworm-slim
COPY --from=builder /node-cert-exporter/bin/node-cert-exporter /